In [3]:
import pandas as pd
import time
import csv
import re
df=pd.read_csv('zf_sPerMeNG_intestine MS2 summary from 48127 at 20230611-182546 20230611-194107 predictedcomp.csv', header =None, sep ='\t')
df.reset_index(drop=True)
df.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11
0,NaN,entry no,MS1scan no,MS1Isolation mass,MS1monoIsomass,chargeState,in [H+],intensityN\/A,StructureN\/A,MS2 Scan no,peaklist,Predicted composition
1,0.0,1,164,532.8548583984375,532.8548583984375,3,1596.5488951953123,ext from peak list,structure na,166,"MS2peaklist(dMass=(94.03176879882812, 95.39357...",[]
2,1.0,2,180,617.8327026367188,617.8327026367188,2,1234.6575652734375,ext from peak list,structure na,182,"MS2peaklist(dMass=(90.79227447509766, 92.70963...",[]
3,2.0,3,183,860.7320556640625,860.7320556640625,2,1720.456271328125,ext from peak list,structure na,185,"MS2peaklist(dMass=(91.41570281982422, 92.77639...",[]
4,3.0,4,188,532.8550415039062,532.8550415039062,3,1596.5494445117188,ext from peak list,structure na,190,"MS2peaklist(dMass=(90.06702423095703, 92.66555...",[]
5,4.0,5,191,775.7548217773438,775.7548217773438,2,1550.5018035546875,ext from peak list,structure na,193,"MS2peaklist(dMass=(92.60694122314453, 92.63258...",[]
6,5.0,6,195,866.7496337890625,866.7496337890625,2,1732.491427578125,ext from peak list,structure na,197,"MS2peaklist(dMass=(91.8111801147461, 92.636970...","[(1731.89, '(1, 5, 2, 0, 0, 0)'), (1729.897, '..."
7,6.0,7,198,690.7764892578125,690.7764892578125,2,1380.545138515625,ext from peak list,structure na,200,"MS2peaklist(dMass=(93.85787963867188, 96.03987...",[]
8,7.0,8,198,872.7678833007812,872.7678833007812,2,1744.5279266015625,ext from peak list,structure na,201,"MS2peaklist(dMass=(93.99453735351562, 100.0247...","[(1744.885, '(0, 4, 2, 0, 1, 0)'), (1742.906, ..."
9,8.0,9,209,945.711181640625,945.711181640625,2,1890.41452328125,ext from peak list,structure na,211,"MS2peaklist(dMass=(97.26182556152344, 102.1366...","[(1888.964, '(2, 3, 2, 0, 1, 0)'), (1888.964, ..."

In [7]:
df.drop(columns=df.columns[0], axis=1, inplace=True)
df.head(5)

,2,3,4,5,6,7,8,9,10,11
0,MS1scan no,MS1Isolation mass,MS1monoIsomass,chargeState,in [H+],intensityN\/A,StructureN\/A,MS2 Scan no,peaklist,Predicted composition
1,164,532.8548583984375,532.8548583984375,3,1596.5488951953123,ext from peak list,structure na,166,"MS2peaklist(dMass=(94.03176879882812, 95.39357...",[]
2,180,617.8327026367188,617.8327026367188,2,1234.6575652734375,ext from peak list,structure na,182,"MS2peaklist(dMass=(90.79227447509766, 92.70963...",[]
3,183,860.7320556640625,860.7320556640625,2,1720.456271328125,ext from peak list,structure na,185,"MS2peaklist(dMass=(91.41570281982422, 92.77639...",[]
4,188,532.8550415039062,532.8550415039062,3,1596.5494445117188,ext from peak list,structure na,190,"MS2peaklist(dMass=(90.06702423095703, 92.66555...",[]